defaults:
- common
- _self_
name: train_vae
_target_: rdp_baseline.workspace_at.TrainATWorkspace
task_name: ${task.name}
shape_meta: ${task.at_shape_meta}
exp_name: default
horizon: ${at.horizon}
n_obs_steps: ${at.n_obs_steps}
n_latency_steps: 0
dataset_obs_steps: ${eval:'${n_obs_steps}*${at.dataset_obs_temporal_downsample_ratio}'}
dataset_obs_temporal_downsample_ratio: ${at.dataset_obs_temporal_downsample_ratio}
n_action_steps: ${eval:'${horizon}-${dataset_obs_steps}+1'}
policy:
  _target_: rdp_baseline.model.VAE
  shape_meta: ${task.shape_meta}
  horizon: ${horizon}
  n_latent_dims: ${at.policy.n_latent_dims}
  mlp_layer_num: ${at.policy.mlp_layer_num}
  use_conv_encoder: ${at.policy.use_conv_encoder}
  conv_latent_dims: ${at.policy.conv_latent_dims}
  conv_layer_num: ${at.policy.conv_layer_num}
  use_rnn_decoder: ${at.policy.use_rnn_decoder}
  rnn_latent_dims: ${at.policy.rnn_latent_dims}
  rnn_layer_num: ${at.policy.rnn_layer_num}
  kl_multiplier: ${at.policy.kl_multiplier}
  n_embed: ${at.policy.n_embed}
  use_vq: ${at.policy.use_vq}
  vqvae_groups: ${at.policy.vqvae_groups}
  eval: ${at.policy.eval}
  act_scale: ${at.policy.act_scale}
  device: ${training.device}
dataloader:
  batch_size: 64
  num_workers: 4
  shuffle: true
  pin_memory: true
  persistent_workers: ${eval:'${dataloader.num_workers} > 0'}
val_dataloader:
  batch_size: 64
  num_workers: 4
  shuffle: false
  pin_memory: true
  persistent_workers: ${eval:'${val_dataloader.num_workers} > 0'}
optimizer:
  _target_: torch.optim.AdamW
  lr: 0.001
  weight_decay: 0.0001
training:
  device: cuda:0
  seed: 42
  debug: false
  resume: false
  lr_scheduler: cosine
  lr_warmup_steps: 100
  num_epochs: 601
  gradient_accumulate_every: 1
  use_ema: false
  freeze_encoder: false
  rollout_every: -1
  checkpoint_every: 10
  val_every: 1
  sample_every: -1
  max_train_steps: null
  max_val_steps: null
  tqdm_interval_sec: 1.0
  mixed_precision: 'no'
logging:
  project: rdp_baseline_at
  resume: false
  mode: offline
  name: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}
  tags:
  - ${name}
  - ${task_name}
  - ${exp_name}
  id: null
  group: null
checkpoint:
  topk:
    monitor_key: train_loss
    mode: min
    k: 1
    format_str: epoch={epoch:04d}-train_loss={train_loss:.6f}.ckpt
  save_last_ckpt: true
  save_last_snapshot: false
hydra:
  job:
    override_dirname: ${name}
    chdir: false
  run:
    dir: ${repo_root}/train_RDP/data/outputs/rdp_baseline/${now:%Y%m%d_%H%M%S}/at
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}
